apiVersion: apps/v1
kind: Deployment
metadata:
  name: yomankum-front-deployment
  namespace: yomankum
  labels:
    app: yomankum-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yomankum-front
  template:
    metadata:
      labels:
        app: yomankum-front
    spec:
      containers:
        - name: front-app
          image: harbor.3trolls.me/yomankum/front/front-app:eef30fab
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: harbor
